[----------]
[ RUN      ] ExceptionTest.ReferenceError
ReferenceError: fooBar is not defined

Stack:
    exception_test.js:23
    share/gjstest/public/register.js:78
    share/gjstest/internal/js/run_test.js:33

[  FAILED  ] ExceptionTest.ReferenceError (1 ms)
[ RUN      ] ExceptionTest.NotAFunctionError
TypeError: object is not a function

Stack:
    exception_test.js:28
    share/gjstest/public/register.js:78
    share/gjstest/internal/js/run_test.js:33

[  FAILED  ] ExceptionTest.NotAFunctionError (1 ms)
[ RUN      ] ExceptionTest.ErrorInMatcherFactory
exception_test.js:32
TypeError: isNearNumber requires two number arguments

[  FAILED  ] ExceptionTest.ErrorInMatcherFactory (1 ms)
[ RUN      ] ExceptionTest.StackOverflow
RangeError: Maximum call stack size exceeded

[  FAILED  ] ExceptionTest.StackOverflow (1 ms)
[ RUN      ] ExceptionTest.UnknownPropertyOnLongFunction
TypeError: Object function foo() {
    return 'asd';
  } has no method 'bar'

Stack:
    exception_test.js:45
    share/gjstest/public/register.js:78
    share/gjstest/internal/js/run_test.js:33

[  FAILED  ] ExceptionTest.UnknownPropertyOnLongFunction (1 ms)
[ RUN      ] ExceptionTest.ObjectLiteralException
{ name: 'SomeException' }

[  FAILED  ] ExceptionTest.ObjectLiteralException (1 ms)
[ RUN      ] ExceptionTest.CustomExceptionClassWithoutStack
{}

[  FAILED  ] ExceptionTest.CustomExceptionClassWithoutStack (1 ms)
[ RUN      ] ExceptionTest.CustomExceptionClassWithStack
{}

Stack:
    exception_test.js:63
    share/gjstest/public/register.js:78
    share/gjstest/internal/js/run_test.js:33

[  FAILED  ] ExceptionTest.CustomExceptionClassWithStack (1 ms)
[ RUN      ] ExceptionTest.CustomExceptionClassWithToString
SomeException

[  FAILED  ] ExceptionTest.CustomExceptionClassWithToString (1 ms)
[ RUN      ] ExceptionTest.PassingTest
[       OK ] ExceptionTest.PassingTest (1 ms)
[ RUN      ] ExceptionTest.ExceptionWithUnsatisfiedMockExpectations
TypeError: object is not a function

Stack:
    exception_test.js:82
    share/gjstest/public/register.js:78
    share/gjstest/internal/js/run_test.js:33

[  FAILED  ] ExceptionTest.ExceptionWithUnsatisfiedMockExpectations (1 ms)
[----------]

[----------]
[ RUN      ] ThrowingConstructorTest.SomeTest
Error: taco

Stack:
    exception_test.js:87
    share/gjstest/public/register.js:77
    share/gjstest/internal/js/run_test.js:33

[  FAILED  ] ThrowingConstructorTest.SomeTest (1 ms)
[----------]

[  FAILED  ]
